trigger:
  - master
pool:
  vmImage: Ubuntu-16.04
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
      architecture: x64
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    displayName: Install requirements
  - script: |
      python train.py
      printenv BUILD_VER
    displayName: Run Image Classifier
    env: 
      TRAINING_KEY: $(TRAININGKEY)
      PREDICTION_KEY: $(PREDICTIONKEY)
      BUILD_VER: $(Build.BuildNumber)
